"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Run.py']
DATA_FILES = [
    'MainWindow.py',
    'Password.ui',
    'PicExtractor.ui',
    'Run.py',
    'me.jpg'
]
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'me.jpg'
}

setup(
    app=APP,
    name='Frame Extractor',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
